// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Analyze(arg1) {
  return window['go']['main']['App']['Analyze'](arg1);
}

export function Apply(arg1) {
  return window['go']['main']['App']['Apply'](arg1);
}

export function DiffForDuplicate(arg1) {
  return window['go']['main']['App']['DiffForDuplicate'](arg1);
}

export function GetDashboardStats() {
  return window['go']['main']['App']['GetDashboardStats']();
}

export function GetProxyStatus() {
  return window['go']['main']['App']['GetProxyStatus']();
}

export function GetRecentRequests(arg1) {
  return window['go']['main']['App']['GetRecentRequests'](arg1);
}

export function GetSetting(arg1) {
  return window['go']['main']['App']['GetSetting'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListModels() {
  return window['go']['main']['App']['ListModels']();
}

export function LogRequest(arg1) {
  return window['go']['main']['App']['LogRequest'](arg1);
}

export function SelectContext(arg1) {
  return window['go']['main']['App']['SelectContext'](arg1);
}

export function SetSetting(arg1, arg2) {
  return window['go']['main']['App']['SetSetting'](arg1, arg2);
}

export function StartProxy() {
  return window['go']['main']['App']['StartProxy']();
}

export function StopProxy() {
  return window['go']['main']['App']['StopProxy']();
}
