// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';

export function Analyze(arg1:api.AnalyzeRequest):Promise<api.AnalyzeResponse>;

export function Apply(arg1:api.ApplyRequest):Promise<api.ApplyResponse>;

export function DiffForDuplicate(arg1:api.DuplicateGroup):Promise<Array<api.DiffLine>>;

export function Greet(arg1:string):Promise<string>;

export function ListModels():Promise<Array<string>>;
