// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';
import {store} from '../models';

export function Analyze(arg1:api.AnalyzeRequest):Promise<api.AnalyzeResponse>;

export function Apply(arg1:api.ApplyRequest):Promise<api.ApplyResponse>;

export function DiffForDuplicate(arg1:api.DuplicateGroup):Promise<Array<api.DiffLine>>;

export function GetDashboardStats():Promise<store.DashboardStats>;

export function GetRecentRequests(arg1:number):Promise<Array<store.Request>>;

export function GetSetting(arg1:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ListModels():Promise<Array<string>>;

export function LogRequest(arg1:store.Request):Promise<void>;

export function SetSetting(arg1:string,arg2:string):Promise<void>;
