// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Analyze(arg1) {
  return window['go']['main']['App']['Analyze'](arg1);
}

export function Apply(arg1) {
  return window['go']['main']['App']['Apply'](arg1);
}

export function DiffForDuplicate(arg1) {
  return window['go']['main']['App']['DiffForDuplicate'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListModels() {
  return window['go']['main']['App']['ListModels']();
}
